# Generated by Django 3.2 on 2021-04-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_alter_postimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.CharField(blank=True, max_length=100, verbose_name='Url картинок'),
        ),
    ]
