# Generated by Django 3.2 on 2021-04-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
