# Generated by Django 3.2 on 2021-04-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_auto_20210417_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('посмотреть', 'Посмотреть'), ('покушать', 'Покушать'), ('развлекательное', 'Развлекательное'), ('познавательное', 'Познавательное'), ('активный отдых', 'Активный отдых'), ('что купить?', 'Что купить?')], max_length=50, verbose_name='Категории'),
        ),
    ]
