# Generated by Django 3.2 on 2021-04-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0012_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Посмотреть'), ('2', 'Покушать'), ('3', 'Развлекательное'), ('4', 'Познавательное'), ('5', 'Активный отдых'), ('6', 'Что купить?')], max_length=50, verbose_name='Категории'),
        ),
    ]
